### ISSUE TITLE
Diseño de Aplicación de Windows Form

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-equipo-mad#1]
[Reporte de Diseño de App con Windows Form.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-equipo-mad/files/14726618/Reporte.de.Diseno.de.App.con.Windows.Form.pdf)

Integrantes:
Marlene Maricela Ososrio Ramírez
Adriana Hernández Martínez
Daniel Velasco López

**Comment by Daisy-GonzalezLita12** [comment]
20%  de 20% bien hecho

**Comment by josealfredo79** [comment]
bien hecho y revisado...
